Repository SeonHyungJo/reactjs-interview-questions-korean, pull requests merged in 2019-05, with the labels that each got.

#7 Translate 11
  README.md
Labels: 확인요청

#8 Translate 12
  README.md
Labels: 확인요청

#9 Translate 13
  README.md
Labels: 확인요청

#10 Translate 06, 07
  README.md
Labels: 머지 요청

#12 Translate 15
  README.md
Labels: 확인요청

#11 Translate 14
  README.md
Labels: 확인요청

#14 🔖 BKJang / Template/ 목차 링크 수정
  README.md
Labels: 확인요청

#15 Translate 08
  README.md
Labels: 확인요청

#16 Translate 16
  README.md
Labels: 확인요청

#17 Translate 17
  README.md
Labels: 확인요청

#18 Translate 09
  README.md
Labels: 확인요청

#19 Translate 10
  README.md
Labels: 확인요청

#20 Translate 18
  README.md
Labels: 확인요청

#24 Translate 25
  README.md
Labels: 확인요청

#25 Translate-26
  README.md
Labels: 확인요청

#21 Translate 22
  README.md
Labels: 확인요청

#22 Translate 23
  README.md
Labels: 확인요청

#23 Translate-24
  README.md
Labels: 확인요청

#26 Translate-27
  README.md
Labels: 확인요청

#28 Translate-29
  README.md
Labels: 확인요청

#29 Translate-30
  README.md
Labels: 확인요청

#30 Translate-31
  README.md
Labels: 확인요청

#32 Translate-33
  README.md
Labels: 확인요청

#34 Translate-34
  README.md
Labels: 확인요청

#35 Translate-36
  README.md
Labels: 확인요청

#31 Translate 32
  README.md
Labels: 확인요청

#33 Translate-35
  README.md
Labels: 확인요청

#36 Translate-37
  README.md
Labels: 확인요청

#27 Translate-28
  README.md
Labels: 제안, 확인요청

#37 Translate-19
  README.md
Labels: 머지 요청

#38 Translate-20
  README.md
Labels: 머지 요청

#39 Translate-21
  README.md
Labels: 머지 요청

#40 Translate-41
  README.md
Labels: 확인요청

#41 Translate-42
  README.md
Labels: 제안, 확인요청

#43 Translate 44
  README.md
Labels: 확인요청

#44 Translate 45
  README.md
Labels: 확인요청

#45 Translate 46
  README.md
Labels: 확인요청

#46 Translate 47
  README.md
Labels: 확인요청
