Repository SeonHyungJo/reactjs-interview-questions-korean, pull requests merged in 2019-07, with the labels that each got.

#68 Translate 65
  README.md
Labels: 확인요청

#69 Translate 66
  README.md
Labels: 확인요청

#63 Translate 60
  README.md
Labels: 확인요청

#70 Translate 67
  README.md
Labels: 확인요청

#72 Translate 69
  README.md
Labels: 확인요청

#73 Translate 70
  README.md
Labels: 확인요청

#74 Translate 71
  README.md
Labels: 확인요청

#71 Translate 68
  README.md
Labels: 확인요청

#76 Translate 73
  README.md
Labels: 확인요청

#77 Translate 74
  README.md
Labels: 확인요청

#78 Translate 75
  README.md
Labels: 확인요청

#79 Translate 76
  README.md
Labels: 확인요청

#80 Translate 77
  README.md
Labels: 확인요청

#81 Translate 78
  README.md
Labels: 확인요청

#82 Translate 79
  README.md
Labels: 확인요청

#84 Translate 81
  README.md
Labels: 확인요청

#85 Translate 82
  README.md
Labels: 확인요청

#87 Translate 84
  README.md
Labels: 확인요청

#88 Translate 85
  README.md
Labels: 확인요청

#89 Translate 86
  README.md
Labels: 확인요청

#90 Translate 87
  README.md
Labels: 확인요청

#92 Translate 89
  README.md
Labels: 확인요청

#93 Translate 90
  README.md
Labels: 확인요청

#94 Translate 91
  README.md
Labels: 확인요청

#75 Translate 72
  README.md
Labels: 머지 요청

#83 Translate 80
  README.md
Labels: 머지 요청

#86 Translate 83
  README.md
Labels: 머지 요청

#91 Translate 88
  README.md
Labels: 머지 요청

#95 Translate 92
  README.md
Labels: 확인요청

#96 Translate 93
  README.md
Labels: 확인요청

#97 Translate 94
  README.md
Labels: 확인요청

#98 Translate 95
  README.md
Labels: 확인요청

#101 Translate 98
  README.md
Labels: 확인요청

#103 Translate 100
  README.md
Labels: 확인요청

#104 Translate 101
  README.md
Labels: 확인요청

#105 Translate 102
  README.md
Labels: 확인요청

#106 Translate 103
  README.md
Labels: 확인요청

#107 Translate 104
  README.md
Labels: 확인요청

#108 Translate 105
  README.md
Labels: 확인요청

#109 Translate 106
  README.md
Labels: 확인요청

#110 Translate 107
  README.md
Labels: 확인요청

#111 Translate 108
  README.md
Labels: 확인요청

#112 Translate 109
  README.md
Labels: 확인요청

#114 Translate 111
  README.md
Labels: 확인요청

#99 Translate 96
  README.md
Labels: 머지 요청

#102 Translate 99
  README.md
Labels: 머지 요청

#113 Translate 110
  README.md
Labels: 머지 요청

#100 Translate 97
  README.md
Labels: 머지 요청

#115 Translate 112
  README.md
Labels: 확인요청

#116 Translate 113
  README.md
Labels: 확인요청

#117 Translate 114
  README.md
Labels: 확인요청

#118 Translate 115
  README.md
Labels: 확인요청

#122 Translate 118
  README.md
Labels: 확인요청

#119 Translate 116
  README.md
Labels: 확인요청

#121 Translate 119
  README.md
Labels: 확인요청

#124 Translate 121
  README.md
Labels: 확인요청

#120 Translate 117
  README.md
Labels: 확인요청

#123 Translate 120
  README.md
Labels: 확인요청

#125 Translate 122
  README.md
Labels: 확인요청

#126 Translate 123
  README.md
Labels: 확인요청

#127 Translate 124
  README.md
Labels: 확인요청

#128 Translate 125
  README.md
Labels: 확인요청

#129 Translate 126
  README.md
Labels: 확인요청

#130 Translate 127
  README.md
Labels: 확인요청

#131 Translate 128
  README.md
Labels: 확인요청

#133 🔖 BKJang / Translate / Translate-39
  README.md
Labels: 확인요청

#132 🔖 BKJang / Translate / Translate-38
  README.md
Labels: 머지 요청

#134 🔖 BKJang / Translate / Translate-40
  README.md
Labels: 머지 요청

#135 Translate 129
  README.md
Labels: 확인요청

#136 Translate 130
  README.md
Labels: 확인요청

#137 Translate 131
  README.md
Labels: 확인요청

#139 Translate 133
  README.md
Labels: 확인요청

#140 Translate 134
  README.md
Labels: 확인요청

#141 Translate 135
  README.md
Labels: 확인요청

#142 Translate-136
  README.md
Labels: 확인요청

#138 ranslate-132
  README.md
Labels: 확인요청

#144 Translate-138
  README.md
Labels: 확인요청

#145 Translate-139
  README.md
Labels: 확인요청

#143 Translate-137
  README.md
Labels: 제안
